; University of Florida
; Author: Bohdan Purtell
; Module: "dune"
; Ordered diagnostic/decoder event arbitration tests.
(library
 (name event_orderer_inline_tests)
 (modules event_orderer_testbench event_orderer_unit_quickcheck_tests event_orderer_expect_tests)
 (inline_tests (flags (:standard -source-tree-root .)))
 (libraries core hardcaml cme_of_hardcaml hardcaml_step_testbench hardcaml_verif)
 (preprocess (pps ppx_hardcaml ppx_jane)))
