# Synthesis script generated by hardcaml_xilinx_reports
proc synthesize { root } {
create_project -in_memory -part xc7a100tcsg324-1
read_verilog [file join $root cme_feed_parser.v]
read_xdc [file join $root cme_feed_parser.xdc]
set_property top cme_feed_parser [current_fileset]
auto_detect_xpm
set_param synth.elaboration.rodinMoreOptions "rt::set_parameter synRetiming true"
synth_design -top cme_feed_parser -mode out_of_context 
opt_design
}
proc write_reports { stage root } {
report_utilization -file [file join $root ${stage}_cme_feed_parser.utilization]
report_timing_summary -file [file join $root ${stage}_cme_feed_parser.timing]
set report_file [open "[file join $root ${stage}_report.txt]" "w"]
current_instance
set setup 0
set hold 0
set clock [get_clocks -filter {NAME == "clock_i"}]
if { [llength $clock] == 1 } {
  set timing_path [get_timing_paths -from $clock -to $clock -max_paths 1 -nworst 1 -setup]
  if { [llength $timing_path] == 1 } {
    set setup [get_property SLACK $timing_path]
  }
  set timing_path [get_timing_paths -from $clock -to $clock -max_paths 1 -nworst 1 -hold]
  if { [llength $timing_path] == 1 } {
    set hold [get_property SLACK $timing_path]
  }
}
puts $report_file "TIMING clock_i $setup $hold"
close $report_file
}
synthesize "/home/wayne/devel/jane/cme/reports/validation/cme_feed_parser"
write_reports "post_synth" "/home/wayne/devel/jane/cme/reports/validation/cme_feed_parser"
place_design
write_reports "post_place" "/home/wayne/devel/jane/cme/reports/validation/cme_feed_parser"
route_design
write_reports "post_route" "/home/wayne/devel/jane/cme/reports/validation/cme_feed_parser"
