(lang dune 3.20)

(name cme_feed_parser)

(generate_opam_files true)

(source
 (github LeEmperor/FeedParser_of_Hardcaml))

(authors "Bohdan Purtell : bohdanpurtell@gmail.com")

(maintainers "Bohdan Purtell : bohdanpurtell@gmail.com")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name cme_feed_parser)
 (synopsis "CME feed parser RTL in Hardcaml")
 (description "RTL implementation of a CME market-data feed parser using Hardcaml")
 (depends
  ocaml
  hardcaml
  ppx_hardcaml)
 (tags
  (hardcaml rtl fpga hft)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
